ACTIVE_PROFILE: dev

DATABASE_HOST: postgres_db
DATABASE_PORT: 5432
DATABASE_NAME: postgres
DATABASE_USERNAME: postgres
DATABASE_PASSWORD: password

JWT_SECRET: bhKfCNHBNncHFysc2Fu2MyOhVJa9L5KsqZX53CN4XCVXZrg0v6oVzSDrOca8WJcp

GOOGLE_CLIENT_ID: 919936836476-82vaceuap3t10do2mnuem0q07qpvol1a.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: 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
GOOGLE_REDIRECT_URI: http://localhost:8080/login/oauth2/code/google

FACEBOOK_CLIENT_ID: 2004666073261983
FACEBOOK_CLIENT_SECRET: 4e33032ad31d77384b87271b04c9a2fa
FACEBOOK_REDIRECT_URI: http://localhost:8080/login/oauth2/code/facebook

FRONT_END_URL: "http://localhost:3000"