name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Pull Docker image
        run: sudo docker pull batsavid/springboot-university:latest

      - name: Delete Old springboot-university docker container
        run: sudo docker rm -f springboot-university || true

      - name: Start Or Refresh Service
        run: |
          if sudo docker ps --filter "name=springboot-university" --format "{{.Names}}" | grep -q "springboot-university"; then
            echo "springboot-university is running, executing custom logic..."
            sudo docker stop springboot-university
            sudo docker rm springboot-university --force
            sudo docker rmi batsavid/springboot-university:latest
            sudo /home/ubuntu/update-app.sh
          else
            echo "springboot-university is not running, starting services with docker-compose..."
            sudo /home/ubuntu/start-dev.sh
          fi

      - name: Remove dangling images
        run: sudo docker image prune -f